name: Build and Release

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/release.yml'
      - '3rd/*'
      - 'include/*'
      - 'src/*'
      - 'modules/*'
      - 'performance/*'
      - 'example/*'
      - 'tests/*'
      - 'cmake/*'
      - 'CMakeLists.txt'
  pull_request:
    paths:
      - '.github/workflows/release.yml'
      - '3rd/*'
      - 'include/*'
      - 'src/*'
      - 'modules/*'
      - 'performance/*'
      - 'example/*'
      - 'tests/*'
      - 'cmake/*'
      - 'CMakeLists.txt'

jobs:
  build-mingw:
    name: Build Windows MinGW
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - qt_arch: win64_mingw
            qt_ver: 6.7.2
            gcc_version: 13.2.0
    env:
      targetName: JX3DPS.dll
    outputs:
      version: ${{ steps.get_version.outputs.VERSION }}
      packageName: ${{ steps.package.outputs.packageName }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Install GCC
        shell: pwsh
        run: |
          .\.github\scripts\install-gcc.ps1 -Version ${{ matrix.gcc_version }}

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.qt_ver }}
          arch: ${{ matrix.qt_arch }}
          cache: 'false'

      - name: Qt and MinGW environment configuration
        shell: pwsh
        run: |
          $QtBin = "${{ env.Qt6_DIR }}/bin"
          echo "$QtBin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Build
        id: build
        shell: bash
        run: |
          export PATH="/c/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/bin:$PATH"
          cmake -S . -B ./build -G "MinGW Makefiles" -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc
          cmake --build ./build --target install --config Release

      - name: Get version from CMake
        id: get_version
        shell: pwsh
        run: |
          cmake -S . -B ./build -DCMAKE_BUILD_TYPE=Release > cmake_output.txt
          $versionLine = Get-Content cmake_output.txt | Select-String -Pattern "VERSION\s*:\s*(.+?)\s*$"
          if ($versionLine) {
            $version = $versionLine.Matches.Groups[1].Value.Trim()
            echo "Extracted version: $version"
            echo "VERSION=$version" >> $env:GITHUB_OUTPUT
          } else {
            echo "Failed to extract version from CMake output"
            exit 1
          }

      - name: Package
        id: package      
        env:
          archiveName: JX3DPS-win64-mingw-${{ steps.get_version.outputs.VERSION }}
        shell: pwsh
        run: |
          & .github\scripts\windows-gcc-publish.ps1 ${env:archiveName} ${env:targetName}
          $name = ${env:archiveName}
          echo "packageName=$name" >> $env:GITHUB_OUTPUT

      - name: Verify artifact
        shell: pwsh
        run: |
          $packageName = "${{ steps.package.outputs.packageName }}"
          if (Test-Path "${packageName}.zip") {
            Write-Output "Artifact ${packageName}.zip created successfully"
          } else {
            Write-Error "Artifact ${packageName}.zip not found"
            exit 1
          }

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.package.outputs.packageName }}
          path: ${{ steps.package.outputs.packageName }}.zip
          retention-days: 1

  generate-changelog:
    name: Generate Changelog and Release
    needs: [build-mingw]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate Changelog
        id: changelog
        run: |
          # 获取最新的标签
          latestTag=$(git describe --tags --abbrev=0)
          
          # 如果没有标签，使用初始提交
          if [ -z "$latestTag" ]; then
            range=$(git rev-list --max-parents=0 HEAD)
          else
            range="${latestTag}..HEAD"
          fi
      
          # 使用 Git 命令获取提交记录，排除合并提交，包括作者信息
          commits=$(git log $range --pretty=format:"- %s by @%an in %h" --reverse --no-merges)
      
          # 如果没有新的提交，使用最新标签到上一个标签的范围
          if [ -z "$commits" ]; then
            previousTag=$(git describe --tags --abbrev=0 ${latestTag}^)
            if [ -n "$previousTag" ]; then
              range="${previousTag}..${latestTag}"
              commits=$(git log $range --pretty=format:"- %s by @%an in %h" --reverse --no-merges)
            fi
          fi
      
          # 按类型分类提交并移除类型前缀，保留作者信息
          featCommits=$(echo "$commits" | grep '^- feat' | sed 's/^- feat: \?/- /')
          fixCommits=$(echo "$commits" | grep '^- fix' | sed 's/^- fix: \?/- /')
          docsCommits=$(echo "$commits" | grep '^- docs' | sed 's/^- docs: \?/- /')
          perfCommits=$(echo "$commits" | grep '^- perf' | sed 's/^- perf: \?/- /')
          refactorCommits=$(echo "$commits" | grep '^- refactor' | sed 's/^- refactor: \?/- /')
          testCommits=$(echo "$commits" | grep '^- test' | sed 's/^- test: \?/- /')
          otherCommits=$(echo "$commits" | grep -v '^- \(feat\|fix\|docs\|perf\|refactor\|test\)' | sed 's/^- [^:]*: \?/- /')
      
          # 构建 changelog
          {
            echo "## CHANGELOG"
            echo
            if [ -n "$featCommits" ]; then
              echo "### Features"
              echo "$featCommits"
              echo
            fi
            
            if [ -n "$fixCommits" ]; then
              echo "### Bug Fixes"
              echo "$fixCommits"
              echo
            fi
            
            if [ -n "$docsCommits" ]; then
              echo "### Documentation"
              echo "$docsCommits"
              echo
            fi
            
            if [ -n "$perfCommits" ]; then
              echo "### Performance Improvements"
              echo "$perfCommits"
              echo
            fi
            
            if [ -n "$refactorCommits" ]; then
              echo "### Refactoring"
              echo "$refactorCommits"
              echo
            fi
            
            if [ -n "$testCommits" ]; then
              echo "### Tests"
              echo "$testCommits"
              echo
            fi
            
            if [ -n "$otherCommits" ]; then
              echo "### Others"
              echo "$otherCommits"
              echo
            fi
          } > changelog.md
      
          echo "changelog_path=changelog.md" >> $GITHUB_OUTPUT

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.build-mingw.outputs.packageName }}

      - name: Display structure of downloaded files
        run: ls -R

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          version="${{ needs.build-mingw.outputs.version }}"
          changelogPath="${{ steps.changelog.outputs.changelog_path }}"
          
          # 使用 GitHub CLI 创建发布
          gh release create $version --title "$version" --notes-file $changelogPath

      - name: Upload Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          version="${{ needs.build-mingw.outputs.version }}"
          packageName="${{ needs.build-mingw.outputs.packageName }}"
          
          # 直接上传下载的zip文件
          if [ -f "${packageName}.zip" ]; then
            gh release upload $version "${packageName}.zip"
            echo "Successfully uploaded ${packageName}.zip to release $version"
          else
            echo "Error: ${packageName}.zip not found"
            ls -R
            exit 1
          fi