name: Windows MinGW and Linux GCC Build

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, review_requested]
    branches:
      - master
  workflow_dispatch:

jobs:
  build-mingw:
    name: Build Windows MinGW
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - qt_arch: win64_mingw
            qt_ver: 6.7.2
            gcc_version: 13.2.0
    env:
      targetName: JX3DPS.dll
    outputs:
      version: ${{ steps.get_version.outputs.VERSION }}
      packageName: ${{ steps.package.outputs.packageName }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Install GCC
        shell: pwsh
        run: |
          .\.github\scripts\install-gcc.ps1 -Version ${{ matrix.gcc_version }}

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.qt_ver }}
          arch: ${{ matrix.qt_arch }}
          cache: 'false'

      - name: Qt and MinGW environment configuration
        shell: pwsh
        run: |
          $QtBin = "${{ env.Qt6_DIR }}/bin"
          echo "$QtBin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Build
        id: build
        shell: bash
        run: |
          export PATH="/c/ProgramData/chocolatey/lib/mingw/tools/install/mingw64/bin:$PATH"
          cmake -S . -B ./build -G "MinGW Makefiles" -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc
          cmake --build ./build --target install --config Release

      - name: Get version from CMake
        id: get_version
        shell: bash
        run: |
          export TZ="Asia/Shanghai"
          timestamp=$(TZ="Asia/Shanghai" git log -1 --format=%cd --date=format:%Y%m%d%H%M)
          cmake -S . -B ./build -DCMAKE_BUILD_TYPE=Release > cmake_output.txt
          version=$(sed -n 's/.*VERSION=\(.*\)/\1/p' cmake_output.txt | head -n 1)
          if [ -z "$version" ]; then
            echo "无法从 CMake 输出中提取版本号"
            exit 1
          fi
          major_minor_version=$(echo $version | cut -d. -f1,2)
          full_version="${major_minor_version}.${timestamp:4:4}.${timestamp:8:4}"
          echo "生成的版本号: $full_version"
          echo "VERSION=$full_version" >> $GITHUB_OUTPUT

      - name: Package
        id: package      
        env:
          archiveName: JX3DPS-win64-mingw-${{ steps.get_version.outputs.VERSION }}
        shell: pwsh
        run: |
          & .github\scripts\windows-gcc-publish.ps1 ${env:archiveName} ${env:targetName}
          $name = ${env:archiveName}
          echo "packageName=$name" >> $env:GITHUB_OUTPUT

      - name: Verify artifact
        shell: pwsh
        run: |
          $packageName = "${{ steps.package.outputs.packageName }}"
          if (Test-Path "${packageName}.zip") {
            Write-Output "Artifact ${packageName}.zip created successfully"
          } else {
            Write-Error "Artifact ${packageName}.zip not found"
            exit 1
          }

      - name: Upload artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          name: ${{ steps.package.outputs.packageName }}
          path: ${{ steps.package.outputs.packageName }}.zip
          retention-days: 1

  build-gcc:
    name: Build Linux GCC
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - gcc_version: 13
    env:
      targetName: JX3DPS.so
    outputs:
      version: ${{ steps.get_version.outputs.VERSION }}
      packageName: ${{ steps.package.outputs.packageName }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Install GCC 13
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install -y gcc-13 g++-13
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 100
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 100
          sudo update-alternatives --set gcc /usr/bin/gcc-13
          sudo update-alternatives --set g++ /usr/bin/g++-13
          gcc --version
          g++ --version

      - name: Build
        id: build
        run: |
          cmake -S . -B ./build -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -DVERSION_BRANCH=release
          cmake --build ./build --target install --config Release --verbose
          echo "Build completed. Checking install directory:"
          find ./build/install -type f

      - name: Check build directory
        run: |
          echo "Checking build directory structure:"
          find ./build -type d
          echo "Checking for JX3DPS.so:"
          find ./build -name JX3DPS.so

      - name: Get version from CMake
        id: get_version
        run: |
          export TZ="Asia/Shanghai"
          timestamp=$(TZ="Asia/Shanghai" git log -1 --format=%cd --date=format:%Y%m%d%H%M)
          cmake -S . -B ./build -DCMAKE_BUILD_TYPE=Release -DVERSION_BRANCH=release > cmake_output.txt
          version=$(sed -n 's/.*VERSION=\(.*\)/\1/p' cmake_output.txt | head -n 1)
          if [ -z "$version" ]; then
            echo "无法从 CMake 输出中提取版本号"
            exit 1
          fi
          major_minor_version=$(echo $version | cut -d. -f1,2)
          full_version="${major_minor_version}.${timestamp:4:4}.${timestamp:8:4}"
          echo "生成的版本号: $full_version"
          echo "VERSION=$full_version" >> $GITHUB_OUTPUT

      - name: Package
        id: package
        env:
          archiveName: JX3DPS-linux-gcc-${{ steps.get_version.outputs.VERSION }}
        run: |
          mkdir -p ${{ env.archiveName }}
          find ./build -name JX3DPS.so -exec cp {} ${{ env.archiveName }}/ \;
          if [ ! -f ${{ env.archiveName }}/JX3DPS.so ]; then
            echo "Error: JX3DPS.so not found"
            exit 1
          fi
          zip -r ${{ env.archiveName }}.zip ${{ env.archiveName }}
          echo "packageName=${{ env.archiveName }}" >> $GITHUB_OUTPUT

      - name: Upload artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          name: ${{ steps.package.outputs.packageName }}
          path: ${{ steps.package.outputs.packageName }}.zip
          retention-days: 1
          
  generate-changelog:
    name: Generate Changelog and Release
    needs: [build-mingw, build-gcc]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0

      - name: Generate Changelog
        id: changelog
        run: |
          # 获取最新的标签
          latestTag=$(git describe --tags --abbrev=0 2>/dev/null || git rev-list --max-parents=0 HEAD)
          
          # 定义范围
          range="${latestTag}..HEAD"
      
          # 使用 Git 命令获取提交记录，排除合并提交，包括作者信息和提交时间戳
          commits=$(git log $range --pretty=format:"%s|@%an|%h|%at" --reverse --no-merges)
      
          # 定义关联数组来存储合并的提交信息
          declare -A feat_commits fix_commits docs_commits perf_commits refactor_commits test_commits other_commits
      
          # 处理每个提交
          while IFS='|' read -r message author hash timestamp; do
            # 提取提交类型和清理后的消息
            if [[ $message =~ ^(feat|fix|docs|perf|refactor|test): ]]; then
              type=${BASH_REMATCH[1]}
              clean_message=${message#$type: }
            else
              type="other"
              # 移除常见的前缀
              clean_message=$(echo "$message" | sed -E 's/^(ci|chore|style|build|revert):\s*//')
            fi
            
            key="${clean_message}|${author}"
            case $type in
              feat)     array_ref="feat_commits"     ;;
              fix)      array_ref="fix_commits"      ;;
              docs)     array_ref="docs_commits"     ;;
              perf)     array_ref="perf_commits"     ;;
              refactor) array_ref="refactor_commits" ;;
              test)     array_ref="test_commits"     ;;
              *)        array_ref="other_commits"    ;;
            esac
            
            if [[ -v ${array_ref}[$key] ]]; then
              eval "${array_ref}[$key]+=';$hash|$timestamp'"
            else
              eval "${array_ref}[$key]='$hash|$timestamp'"
            fi
          done <<< "$commits"
      
          # 格式化提交
          format_commits() {
            local -n commit_array=$1
            local title=$2
            local formatted=""
            
            # 创建一个临时数组来存储排序后的提交
            declare -a sorted_commits
            for key in "${!commit_array[@]}"; do
              IFS='|' read -r message author <<< "$key"
              hashes_timestamps="${commit_array[$key]}"
              IFS=';' read -ra entries <<< "$hashes_timestamps"
              for entry in "${entries[@]}"; do
                IFS='|' read -r hash timestamp <<< "$entry"
                sorted_commits+=("$timestamp|$message|$author|$hash")
              done
            done
            
            # 按时间戳排序
            IFS=$'\n' sorted_commits=($(sort <<<"${sorted_commits[*]}"))
            unset IFS
            
            # 格式化排序后的提交
            local prev_message=""
            local hashes=""
            for entry in "${sorted_commits[@]}"; do
              IFS='|' read -r timestamp message author hash <<< "$entry"
              if [[ "$message" != "$prev_message" && -n "$prev_message" ]]; then
                formatted+="- $prev_message by $prev_author in $hashes"$'\n'
                hashes=""
              fi
              hashes+="$hash "
              prev_message="$message"
              prev_author="$author"
            done
            if [[ -n "$prev_message" ]]; then
              formatted+="- $prev_message by $prev_author in $hashes"$'\n'
            fi
            
            if [ -n "$formatted" ]; then
              echo "### $title"
              echo "$formatted"
            fi
          }
      
          # 构建 changelog
          {
            echo "## CHANGELOG"
            echo
            format_commits feat_commits "Features"
            format_commits fix_commits "Bug Fixes"
            format_commits docs_commits "Documentation"
            format_commits perf_commits "Performance Improvements"
            format_commits refactor_commits "Refactoring"
            format_commits test_commits "Tests"
            format_commits other_commits "Others"
          } > changelog.md
      
          echo "changelog_path=changelog.md" >> $GITHUB_OUTPUT

      - name: Download Windows artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: ${{ needs.build-mingw.outputs.packageName }}

      - name: Download Linux artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: ${{ needs.build-gcc.outputs.packageName }}

      - name: Display structure of downloaded files
        run: ls -R

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          version="${{ needs.build-mingw.outputs.version }}"
          changelogPath="${{ steps.changelog.outputs.changelog_path }}"
          
          # 使用 GitHub CLI 创建发布
          gh release create $version --title "$version" --notes-file $changelogPath

      - name: Upload Release Assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          version="${{ needs.build-mingw.outputs.version }}"
          windows_package="${{ needs.build-mingw.outputs.packageName }}"
          linux_package="${{ needs.build-gcc.outputs.packageName }}"
          
          if [ -f "${windows_package}.zip" ]; then
            gh release upload $version "${windows_package}.zip"
            echo "Successfully uploaded ${windows_package}.zip to release $version"
          else
            echo "Error: ${windows_package}.zip not found"
            ls -R
            exit 1
          fi

          if [ -f "${linux_package}.zip" ]; then
            gh release upload $version "${linux_package}.zip"
            echo "Successfully uploaded ${linux_package}.zip to release $version"
          else
            echo "Error: ${linux_package}.zip not found"
            ls -R
            exit 1
          fi